spring.application.name=crypto-portfolio-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/cryptodb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update