CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     created_at TIMESTAMP WITH TIME ZONE,
                                     email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
                             );

CREATE TABLE IF NOT EXISTS coins (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
    symbol VARCHAR(255) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS holdings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        created_at TIMESTAMP WITH TIME ZONE,
                                        quantity NUMERIC(19,8) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
                             user_id BIGINT NOT NULL,
                             coin_id BIGINT NOT NULL,
                             average_buy_price_usd NUMERIC(19,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT fko0m56qvi5yyl5ikolvm7ih20o FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fkg1wfrsj0xte0p5dwke7clrwxc FOREIGN KEY (coin_id) REFERENCES coins(id)
    );

CREATE TABLE IF NOT EXISTS transactions (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                            price_usd NUMERIC(19,2) NOT NULL,
    quantity NUMERIC(19,8) NOT NULL,
    realised_profit_usd NUMERIC(19,2) NOT NULL,
    total_value_usd NUMERIC(19,2) NOT NULL,
    type VARCHAR(10) NOT NULL,
    coin_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_transactions_coin FOREIGN KEY (coin_id) REFERENCES coins(id),
    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users(id)
    );

CREATE TABLE IF NOT EXISTS user_roles (
                                          user_id BIGINT NOT NULL,
                                          roles VARCHAR(255),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id)
    );