CREATE TABLE IF NOT EXISTS portfolio_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    snapshot_at TIMESTAMP WITH TIME ZONE NOT NULL,
    total_invested_usd NUMERIC(19,2) NOT NULL,
    total_current_value_usd NUMERIC(19,2) NOT NULL,
    total_profit_loss_usd NUMERIC(19,2) NOT NULL,
    CONSTRAINT fk_portfolio_snapshots_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_portfolio_snapshots_user_snapshot_at
    ON portfolio_snapshots (user_id, snapshot_at);
